definitions:
  models.MetricResponse:
    properties:
      clicks:
        type: integer
      closed_won:
        type: integer
      cost:
        type: number
      cpa:
        description: Cost Per Acquisition = cost / leads
        type: number
      cpc:
        description: Métricas calculadas
        type: number
      cvr_lead_to_opp:
        description: Conversion Rate Lead to Opportunity
        type: number
      cvr_opp_to_won:
        description: Conversion Rate Opportunity to Won
        type: number
      leads:
        type: integer
      opportunities:
        type: integer
      revenue:
        type: number
      roas:
        description: Return on Ad Spend = revenue / cost
        type: number
      utm_campaign:
        type: string
      utm_medium:
        type: string
      utm_source:
        type: string
    type: object
info:
  contact: {}
paths:
  /ingest/run:
    post:
      consumes:
      - application/json
      description: Ejecuta un proceso ETL que extrae datos de ADS y CRM y guarda los
        resultados. Soporta filtrado por fecha con el parámetro 'since'.
      parameters:
      - description: Fecha desde la cual filtrar datos (YYYY-MM-DD)
        in: query
        name: since
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: ETL completado correctamente
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Parámetro de fecha inválido
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Error interno del servidor
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Ejecuta el proceso ETL de ingestión
      tags:
      - ingest
  /metrics:
    get:
      consumes:
      - application/json
      description: Retorna un listado de métricas con información de campañas, clics,
        costo, leads, ventas y métricas calculadas (CPC, CPA, CVR, ROAS).
      produces:
      - application/json
      responses:
        "200":
          description: Lista de métricas con cálculos incluidos
          schema:
            items:
              $ref: '#/definitions/models.MetricResponse'
            type: array
        "500":
          description: Error interno del servidor
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtiene métricas almacenadas con cálculos derivados
      tags:
      - metrics
swagger: "2.0"
