definitions:
  api.HealthResponse:
    properties:
      service:
        type: string
      status:
        type: string
      time:
        type: string
    type: object
  api.ReadinessResponse:
    properties:
      checks:
        additionalProperties:
          type: string
        type: object
      service:
        type: string
      status:
        type: string
      time:
        type: string
    type: object
  models.MetricResponse:
    properties:
      clicks:
        type: integer
      closed_won:
        type: integer
      cost:
        type: number
      cpa:
        description: Cost Per Acquisition = cost / leads
        type: number
      cpc:
        description: Métricas calculadas
        type: number
      cvr_lead_to_opp:
        description: Conversion Rate Lead to Opportunity
        type: number
      cvr_opp_to_won:
        description: Conversion Rate Opportunity to Won
        type: number
      leads:
        type: integer
      opportunities:
        type: integer
      revenue:
        type: number
      roas:
        description: Return on Ad Spend = revenue / cost
        type: number
      utm_campaign:
        type: string
      utm_medium:
        type: string
      utm_source:
        type: string
    type: object
info:
  contact: {}
paths:
  /healthz:
    get:
      consumes:
      - application/json
      description: Verifica que el servicio esté funcionando
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.HealthResponse'
      summary: Health check básico
      tags:
      - health
  /ingest/run:
    post:
      consumes:
      - application/json
      description: Ejecuta un proceso ETL que extrae datos de ADS y CRM y guarda los
        resultados. Soporta filtrado por fecha con el parámetro 'since'.
      parameters:
      - description: Fecha desde la cual filtrar datos (YYYY-MM-DD)
        in: query
        name: since
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: ETL completado correctamente
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Parámetro de fecha inválido
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Error interno del servidor
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Ejecuta el proceso ETL de ingestión
      tags:
      - ingest
  /metrics:
    get:
      consumes:
      - application/json
      description: Retorna un listado de métricas con información de campañas, clics,
        costo, leads, ventas y métricas calculadas (CPC, CPA, CVR, ROAS).
      produces:
      - application/json
      responses:
        "200":
          description: Lista de métricas con cálculos incluidos
          schema:
            items:
              $ref: '#/definitions/models.MetricResponse'
            type: array
        "500":
          description: Error interno del servidor
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtiene métricas almacenadas con cálculos derivados
      tags:
      - metrics
  /metrics/channel:
    get:
      consumes:
      - application/json
      description: Retorna métricas filtradas por canal con soporte para fechas y
        paginación
      parameters:
      - description: Fecha desde (YYYY-MM-DD)
        in: query
        name: from
        type: string
      - description: Fecha hasta (YYYY-MM-DD)
        in: query
        name: to
        type: string
      - description: Canal específico
        in: query
        name: channel
        type: string
      - default: 50
        description: Límite de resultados
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset para paginación
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.MetricResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtiene métricas por canal
      tags:
      - metrics
  /metrics/funnel:
    get:
      consumes:
      - application/json
      description: Retorna métricas de conversión filtradas por campaña con soporte
        para fechas y paginación
      parameters:
      - description: Fecha desde (YYYY-MM-DD)
        in: query
        name: from
        type: string
      - description: Fecha hasta (YYYY-MM-DD)
        in: query
        name: to
        type: string
      - description: Campaña específica
        in: query
        name: utm_campaign
        type: string
      - default: 50
        description: Límite de resultados
        in: query
        name: limit
        type: integer
      - default: 0
        description: Offset para paginación
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.MetricResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Obtiene métricas de funnel por campaña
      tags:
      - metrics
  /readyz:
    get:
      consumes:
      - application/json
      description: Verifica que el servicio esté listo para recibir tráfico
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReadinessResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/api.ReadinessResponse'
      summary: Readiness check
      tags:
      - health
swagger: "2.0"
